import type {
  MarketingCampaign,
  MarketingSetting,
  MarketingTaskTemplate,
} from "@/lib/market/marketing-types"

function nowIso() {
  return new Date().toISOString()
}

export function getDefaultMarketingSettings(): MarketingSetting[] {
  const createdAt = nowIso()

  return [
    {
      id: "setting-invite-signup-cash-reward",
      key: "invite_signup_cash_reward",
      value: 5,
      description: "Cash reward for inviter after invitee registration",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-first-order-cash-reward",
      key: "invite_first_order_cash_reward",
      value: 10,
      description: "Cash reward for inviter after invitee first paid order",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-seven-day-login-points-reward",
      key: "invite_seven_day_login_points_reward",
      value: 50,
      description: "Points reward for inviter after invitee 7-day login streak",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-points-decay-grace-days",
      key: "invite_points_decay_grace_days",
      value: 30,
      description: "Grace period before invite points decay starts",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-points-decay-daily-rate",
      key: "invite_points_decay_daily_rate",
      value: 1,
      description: "Daily invite points decay percentage after grace period",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-points-decay-max-rate",
      key: "invite_points_decay_max_rate",
      value: 50,
      description: "Maximum cumulative invite points decay percentage",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-withdraw-min-amount",
      key: "withdraw_min_amount",
      value: 20,
      description: "Minimum cash withdrawal threshold",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-manual-review-required",
      key: "manual_review_required",
      value: true,
      description: "Whether high-risk rewards and withdrawals require manual review",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-monthly-login-reward",
      key: "cash_monthly_login_reward",
      value: 1,
      description: "Retention cash bonus for a qualified monthly login",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-withdraw-requires-monthly-login",
      key: "cash_withdraw_requires_monthly_login",
      value: true,
      description: "Whether withdrawal requires at least one login in the current month",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-inactivity-preview-days",
      key: "cash_inactivity_preview_days",
      value: 30,
      description: "Cash inactivity preview window in days",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-inactivity-deduction-daily-rate",
      key: "cash_inactivity_deduction_daily_rate",
      value: 1,
      description: "Daily cash deduction percentage after inactivity window",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-inactivity-deduction-max-rate",
      key: "cash_inactivity_deduction_max_rate",
      value: 50,
      description: "Maximum cumulative cash deduction percentage",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-points-inactivity-preview-days",
      key: "points_inactivity_preview_days",
      value: 30,
      description: "Points inactivity preview window in days",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-points-expiry-days",
      key: "points_expiry_days",
      value: 180,
      description: "Points clear window for long-term inactivity",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-points-redeem-offset-rate",
      key: "points_redeem_offset_rate",
      value: 100,
      description: "Points required for one unit of order deduction",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-points-order-paid-reward",
      key: "points_order_paid_reward",
      value: 100,
      description: "Points reward after a paid order",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ad-watch-min-seconds",
      key: "ad_watch_min_seconds",
      value: 15,
      description: "Minimum rewarded ad watch duration in seconds",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ad-watch-daily-limit",
      key: "ad_watch_daily_limit",
      value: 5,
      description: "Shared daily limit for rewarded ad tasks",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ad-watch-cash-reward",
      key: "ad_watch_cash_reward",
      value: 1,
      description: "Cash reward for one rewarded ad completion",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ad-watch-points-reward",
      key: "ad_watch_points_reward",
      value: 30,
      description: "Points reward for one rewarded ad completion",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ad-watch-ai-quota-reward",
      key: "ad_watch_ai_quota_reward",
      value: 20,
      description: "AI quota reward for one rewarded ad completion",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-login-streak-vip-days",
      key: "login_streak_vip_days",
      value: 3,
      description: "VIP days granted after a login streak reward",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ai-quota-relief-points-reward",
      key: "ai_quota_relief_points_reward",
      value: 15,
      description: "Points granted when AI quota is exhausted to guide fallback actions",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-ai-quota-relief-vip-days",
      key: "ai_quota_relief_vip_days",
      value: 1,
      description: "VIP days granted when AI quota is exhausted",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-vip-upgrade-bonus-days",
      key: "vip_upgrade_bonus_days",
      value: 30,
      description: "Extra VIP days granted after a subscription upgrade",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-vip-flash-sale-discount-rate",
      key: "vip_flash_sale_discount_rate",
      value: 20,
      description: "Limited-time VIP upgrade discount percentage",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-vip-upsell-window-days",
      key: "vip_upsell_window_days",
      value: 7,
      description: "Days for a limited-time VIP upsell window",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-tier",
      key: "invite_partner_tier",
      value: "partner_package",
      description: "Default invite partner tier",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-product",
      key: "invite_partner_product",
      value: "orbitchat",
      description: "Default product bound to partner invite codes",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-product-cost",
      key: "invite_partner_product_cost",
      value: 0,
      description: "Default product cost used for partner commission net profit",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-benefit-months",
      key: "invite_partner_benefit_months",
      value: 36,
      description: "Default membership months granted to partner codes",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-fan-discount-rate",
      key: "invite_partner_fan_discount_rate",
      value: 20,
      description: "Default discount percentage for linked audience codes",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-partner-order-commission-rate",
      key: "invite_partner_order_commission_rate",
      value: 15,
      description: "Default partner order commission percentage",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-purchase-price",
      key: "invite_coupon_purchase_price",
      value: 9.9,
      description: "Default invite coupon purchase price",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-product-cost",
      key: "invite_coupon_product_cost",
      value: 0,
      description: "Default invite coupon product cost used for commission net profit",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-discount-type",
      key: "invite_coupon_discount_type",
      value: "percentage",
      description: "Default invite coupon discount type",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-discount-value",
      key: "invite_coupon_discount_value",
      value: 15,
      description: "Default invite coupon discount value",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-min-purchase",
      key: "invite_coupon_min_purchase",
      value: 99,
      description: "Default invite coupon minimum purchase threshold",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-valid-days",
      key: "invite_coupon_valid_days",
      value: 30,
      description: "Default invite coupon validity in days",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-invite-coupon-default-user-id",
      key: "invite_coupon_default_user_id",
      value: "",
      description: "Default bound user for invite coupons",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-risk-device-threshold",
      key: "risk_multi_account_threshold",
      value: 3,
      description: "Device threshold for multi-account risk detection",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-risk-ip-frequency-threshold",
      key: "risk_ip_frequency_threshold",
      value: 5,
      description: "IP event frequency threshold for risk detection",
      createdAt,
      updatedAt: createdAt,
    },
  ]
}

export function getDefaultMarketingCampaigns(): MarketingCampaign[] {
  const createdAt = nowIso()

  return [
    {
      id: "campaign-invite-cash-sprint",
      slug: "invite-cash-sprint",
      name: "Invite cash sprint",
      description: "Core referral growth playbook for registration, first order, and retention rewards",
      campaignType: "referral",
      productScope: ["orbitchat", "ai", "ecommerce"],
      highlight: "Invite signup cash, first order cash, 7-day login points",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 10,
      rules: {
        manualReview: true,
        withdrawalMinAmount: 20,
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-cash-retention-engine",
      slug: "cash-retention-engine",
      name: "Cash retention engine",
      description: "Retention-first cash rules for monthly login, withdrawal threshold, and inactivity deduction preview",
      campaignType: "retention",
      productScope: ["orbitchat", "ai", "ecommerce"],
      highlight: "Monthly login reward, 20-unit withdrawal gate, inactivity deduction rules",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 20,
      rules: {
        monthlyLoginRequired: true,
        inactivityPreviewDays: 30,
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-ad-reward-boost",
      slug: "ad-reward-boost",
      name: "Ad reward boost",
      description: "Rewarded ad loop for cash red packets, points, AI quota, and lightweight recovery",
      campaignType: "ad_reward",
      productScope: ["orbitchat", "ai"],
      highlight: "15-second rewarded ad for cash, points, and AI quota",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 30,
      rules: {
        callbackMode: "mock",
        antiFraud: "freeze-first",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-login-grand-prize",
      slug: "login-grand-prize",
      name: "Login grand prize",
      description: "Consecutive login campaign with visible milestone copy and premium prize storytelling",
      campaignType: "engagement",
      productScope: ["orbitchat", "ai", "ecommerce"],
      highlight: "7-day VIP reward and 30-day grand prize narrative",
      status: "draft",
      startAt: null,
      endAt: null,
      sortOrder: 40,
      rules: {
        previewOnly: true,
        prizePool: "iPhone 17",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-points-loyalty-loop",
      slug: "points-loyalty-loop",
      name: "Points loyalty loop",
      description: "Points accrual and redemption engine for orders, referrals, and reactivation",
      campaignType: "loyalty",
      productScope: ["orbitchat", "ai", "ecommerce"],
      highlight: "Order points, invite points, inactivity warning, redemption offset",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 50,
      rules: {
        redeemOffsetRate: 100,
        expiryDays: 180,
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-vip-upgrade-flash-sale",
      slug: "vip-upgrade-flash-sale",
      name: "VIP upgrade flash sale",
      description: "Membership upgrade journey for AI quota exhaustion, bonus days, and limited-time offers",
      campaignType: "upsell",
      productScope: ["orbitchat", "ai"],
      highlight: "Quota exhausted fallback, bonus VIP days, limited discount upsell",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 60,
      rules: {
        upsellWindowDays: 7,
        discountRate: 20,
      },
      createdAt,
      updatedAt: createdAt,
    },
  ]
}

export function getDefaultMarketingTaskTemplates(): MarketingTaskTemplate[] {
  const createdAt = nowIso()

  return [
    {
      id: "template-referral-register-cash",
      slug: "referral-register-cash",
      campaignSlug: "invite-cash-sprint",
      name: "Invite signup cash",
      description: "Reward the inviter with cash after an invited friend completes registration",
      taskType: "referral_register",
      eventType: "referral.registered",
      rewardAsset: "cash",
      rewardAmount: 5,
      rewardRecipient: "payload.inviterUserId",
      thresholdValue: 1,
      thresholdUnit: "person",
      dailyLimit: 20,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "manual_review",
      riskRules: {
        freezeOn: ["self_referral", "multi_account_device", "matched_risk_list"],
      },
      products: ["orbitchat", "ai", "ecommerce"],
      meta: {
        label: "signup_cash",
      },
      status: "active",
      sortOrder: 10,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-referral-first-order-cash",
      slug: "referral-first-order-cash",
      campaignSlug: "invite-cash-sprint",
      name: "Invite first order cash",
      description: "Reward the inviter with cash after the invitee completes a first paid order",
      taskType: "referral_first_order",
      eventType: "order.paid",
      rewardAsset: "cash",
      rewardAmount: 10,
      rewardRecipient: "payload.inviterUserId",
      thresholdValue: 1,
      thresholdUnit: "order",
      dailyLimit: 20,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "manual_review",
      riskRules: {
        freezeOn: ["self_referral", "multi_account_device", "matched_risk_list"],
      },
      products: ["orbitchat", "ai", "ecommerce"],
      meta: {
        firstPaidOrderOnly: true,
      },
      status: "active",
      sortOrder: 20,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-referral-seven-day-login-points",
      slug: "referral-seven-day-login-points",
      campaignSlug: "invite-cash-sprint",
      name: "Invite 7-day login points",
      description: "Reward the inviter with points after the invitee completes a 7-day login streak",
      taskType: "referral_login_streak",
      eventType: "user.login",
      rewardAsset: "points",
      rewardAmount: 50,
      rewardRecipient: "payload.inviterUserId",
      thresholdValue: 7,
      thresholdUnit: "day",
      dailyLimit: 1,
      lifetimeLimit: 1,
      recurrence: "streak",
      decayPolicy: "preview_only",
      riskRules: {
        freezeOn: ["self_referral", "multi_account_device", "matched_risk_list"],
      },
      products: ["orbitchat", "ai", "ecommerce"],
      meta: {
        triggerSubject: "invitee",
      },
      status: "active",
      sortOrder: 30,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ad-watch-cash",
      slug: "ad-watch-cash",
      campaignSlug: "ad-reward-boost",
      name: "Rewarded ad cash packet",
      description: "Grant a small cash packet after a rewarded ad completion",
      taskType: "ad_watch",
      eventType: "ad.completed",
      rewardAsset: "cash",
      rewardAmount: 1,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "watch",
      dailyLimit: 5,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "manual_review",
      riskRules: {
        freezeOn: ["ad_velocity_spike", "matched_risk_list"],
      },
      products: ["orbitchat", "ai"],
      meta: {
        minimumWatchSeconds: 15,
      },
      status: "active",
      sortOrder: 40,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ad-watch-ai-quota",
      slug: "ad-watch-ai-quota",
      campaignSlug: "ad-reward-boost",
      name: "Rewarded ad AI quota",
      description: "Grant AI quota after a rewarded ad completion",
      taskType: "ad_watch",
      eventType: "ad.completed",
      rewardAsset: "ai_quota",
      rewardAmount: 20,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "watch",
      dailyLimit: 5,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["ad_velocity_spike", "matched_risk_list"],
      },
      products: ["ai"],
      meta: {
        minimumWatchSeconds: 15,
      },
      status: "active",
      sortOrder: 50,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ad-watch-points",
      slug: "ad-watch-points",
      campaignSlug: "ad-reward-boost",
      name: "Rewarded ad points",
      description: "Grant points after a rewarded ad completion",
      taskType: "ad_watch",
      eventType: "ad.completed",
      rewardAsset: "points",
      rewardAmount: 30,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "watch",
      dailyLimit: 5,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["ad_velocity_spike", "matched_risk_list"],
      },
      products: ["orbitchat", "ai"],
      meta: {
        minimumWatchSeconds: 15,
      },
      status: "active",
      sortOrder: 60,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-login-streak-vip",
      slug: "login-streak-vip",
      campaignSlug: "login-grand-prize",
      name: "Login streak VIP",
      description: "Grant VIP days after a 7-day login streak and keep the grand prize story visible",
      taskType: "login_streak",
      eventType: "user.login",
      rewardAsset: "vip_duration",
      rewardAmount: 3,
      rewardRecipient: "actor",
      thresholdValue: 7,
      thresholdUnit: "day",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "streak",
      decayPolicy: "preview_only",
      riskRules: {
        freezeOn: [],
      },
      products: ["orbitchat", "ai", "ecommerce"],
      meta: {
        prizeCopy: "Complete a 30-day streak to join the iPhone 17 grand prize story",
        projectionSubscriptionType: "monthly",
      },
      status: "active",
      sortOrder: 70,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-order-paid-points",
      slug: "order-paid-points",
      campaignSlug: "points-loyalty-loop",
      name: "Order paid points",
      description: "Return points to the buyer after a paid order",
      taskType: "order_paid",
      eventType: "order.paid",
      rewardAsset: "points",
      rewardAmount: 100,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "order",
      dailyLimit: null,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["matched_risk_list"],
      },
      products: ["ecommerce", "ai", "orbitchat"],
      meta: {
        minimumOrderAmount: 20,
      },
      status: "active",
      sortOrder: 80,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-subscription-upgrade-vip",
      slug: "subscription-upgrade-vip",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "Subscription upgrade VIP bonus",
      description: "Grant bonus VIP days after a subscription upgrade",
      taskType: "subscription_upgrade",
      eventType: "subscription.upgraded",
      rewardAsset: "vip_duration",
      rewardAmount: 30,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "upgrade",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "none",
      riskRules: {
        freezeOn: [],
      },
      products: ["orbitchat", "ai"],
      meta: {
        projectionSubscriptionType: "monthly",
      },
      status: "active",
      sortOrder: 90,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ai-quota-exhausted-relief",
      slug: "ai-quota-exhausted-relief",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "AI quota exhausted points relief",
      description: "Grant points when AI quota is exhausted to guide fallback tasks such as invite or ad watch",
      taskType: "quota_relief",
      eventType: "ai.quota.exhausted",
      rewardAsset: "points",
      rewardAmount: 15,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "trigger",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: [],
      },
      products: ["ai"],
      meta: {
        followUpTasks: ["ad-watch-ai-quota", "ad-watch-cash", "referral-register-cash"],
      },
      status: "active",
      sortOrder: 100,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ai-quota-exhausted-vip-trial",
      slug: "ai-quota-exhausted-vip-trial",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "AI quota exhausted VIP trial",
      description: "Grant a short VIP trial after AI quota exhaustion to improve upgrade conversion",
      taskType: "quota_relief_vip",
      eventType: "ai.quota.exhausted",
      rewardAsset: "vip_duration",
      rewardAmount: 1,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "trigger",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: [],
      },
      products: ["ai"],
      meta: {
        upsellTrigger: "flash_sale",
      },
      status: "active",
      sortOrder: 110,
      createdAt,
      updatedAt: createdAt,
    },
  ]
}
