import type {
  MarketingCampaign,
  MarketingSetting,
  MarketingTaskTemplate,
} from "@/lib/market/marketing-types"

function nowIso() {
  return new Date().toISOString()
}

export function getDefaultMarketingSettings(): MarketingSetting[] {
  const createdAt = nowIso()

  return [
    {
      id: "setting-withdraw-min-amount",
      key: "withdraw_min_amount",
      value: 20,
      description: "现金提现最低门槛（元）",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-manual-review-required",
      key: "manual_review_required",
      value: true,
      description: "提现与高风险奖励必须人工复核",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-points-preview-days",
      key: "points_inactivity_preview_days",
      value: 30,
      description: "积分清零预览天数",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-cash-preview-days",
      key: "cash_inactivity_preview_days",
      value: 30,
      description: "现金扣减预览天数",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-risk-device-threshold",
      key: "risk_multi_account_threshold",
      value: 3,
      description: "同设备命中多账号风控阈值",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "setting-risk-ip-frequency-threshold",
      key: "risk_ip_frequency_threshold",
      value: 5,
      description: "同 IP 高频事件风控阈值",
      createdAt,
      updatedAt: createdAt,
    },
  ]
}

export function getDefaultMarketingCampaigns(): MarketingCampaign[] {
  const createdAt = nowIso()

  return [
    {
      id: "campaign-invite-cash-sprint",
      slug: "invite-cash-sprint",
      name: "邀请裂变现金冲刺",
      description: "面向 OrbitChat 与 AI 工具的通用拉新现金活动",
      campaignType: "referral",
      productScope: ["orbitchat", "ai"],
      highlight: "邀请注册、邀请激活、现金门槛提现",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 10,
      rules: {
        manualReview: true,
        withdrawalMinAmount: 20,
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-ad-reward-boost",
      slug: "ad-reward-boost",
      name: "广告激励补能计划",
      description: "通过模拟广告完成回调，发放积分、次数与会员时长",
      campaignType: "ad_reward",
      productScope: ["orbitchat", "ai"],
      highlight: "15 秒激励广告、积分与 AI 次数发放",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 20,
      rules: {
        callbackMode: "mock",
        antiFraud: "freeze-first",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-login-grand-prize",
      slug: "login-grand-prize",
      name: "连续登录大奖池",
      description: "以连续登录和高门槛积分兑换为噱头的促活活动",
      campaignType: "engagement",
      productScope: ["orbitchat", "ai", "ecommerce"],
      highlight: "连续登录冲刺 iPhone 17、月登录保活提醒",
      status: "draft",
      startAt: null,
      endAt: null,
      sortOrder: 30,
      rules: {
        previewOnly: true,
        prizePool: "iPhone 17",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "campaign-vip-upgrade-flash-sale",
      slug: "vip-upgrade-flash-sale",
      name: "会员升级限时折扣",
      description: "针对 AI 与 OrbitChat 的会员升级与时间补贴活动",
      campaignType: "upsell",
      productScope: ["orbitchat", "ai"],
      highlight: "升级会员、补领会员时长、限时折扣推送",
      status: "active",
      startAt: null,
      endAt: null,
      sortOrder: 40,
      rules: {
        upsellWindowDays: 7,
      },
      createdAt,
      updatedAt: createdAt,
    },
  ]
}

export function getDefaultMarketingTaskTemplates(): MarketingTaskTemplate[] {
  const createdAt = nowIso()

  return [
    {
      id: "template-referral-register-cash",
      slug: "referral-register-cash",
      campaignSlug: "invite-cash-sprint",
      name: "邀请注册现金奖励",
      description: "好友完成注册后，给邀请人发放现金奖励",
      taskType: "referral_register",
      eventType: "referral.registered",
      rewardAsset: "cash",
      rewardAmount: 2,
      rewardRecipient: "payload.inviterUserId",
      thresholdValue: 1,
      thresholdUnit: "person",
      dailyLimit: 20,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "manual_review",
      riskRules: {
        freezeOn: ["self_referral", "multi_account_device", "matched_risk_list"],
      },
      products: ["orbitchat", "ai"],
      meta: {
        label: "拉新首奖",
      },
      status: "active",
      sortOrder: 10,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-referral-activate-points",
      slug: "referral-activate-points",
      campaignSlug: "invite-cash-sprint",
      name: "邀请激活积分奖励",
      description: "好友完成首个激活动作后，为邀请人补发积分",
      taskType: "referral_activate",
      eventType: "referral.activated",
      rewardAsset: "points",
      rewardAmount: 60,
      rewardRecipient: "payload.inviterUserId",
      thresholdValue: 1,
      thresholdUnit: "person",
      dailyLimit: 30,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "preview_only",
      riskRules: {
        freezeOn: ["self_referral", "multi_account_device", "matched_risk_list"],
      },
      products: ["orbitchat", "ai"],
      meta: {
        label: "二跳激活",
      },
      status: "active",
      sortOrder: 20,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ad-watch-ai-quota",
      slug: "ad-watch-ai-quota",
      campaignSlug: "ad-reward-boost",
      name: "看广告领取 AI 次数",
      description: "完成一次模拟广告观看后，为当前用户补发 AI 次数",
      taskType: "ad_watch",
      eventType: "ad.completed",
      rewardAsset: "ai_quota",
      rewardAmount: 20,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "watch",
      dailyLimit: 3,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["ad_velocity_spike", "matched_risk_list"],
      },
      products: ["ai"],
      meta: {
        minimumWatchSeconds: 15,
      },
      status: "active",
      sortOrder: 30,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ad-watch-points",
      slug: "ad-watch-points",
      campaignSlug: "ad-reward-boost",
      name: "看广告领取积分",
      description: "完成一次模拟广告观看后，为当前用户发放积分",
      taskType: "ad_watch",
      eventType: "ad.completed",
      rewardAsset: "points",
      rewardAmount: 30,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "watch",
      dailyLimit: 5,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["ad_velocity_spike", "matched_risk_list"],
      },
      products: ["orbitchat", "ai"],
      meta: {
        minimumWatchSeconds: 15,
      },
      status: "active",
      sortOrder: 40,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-login-streak-vip",
      slug: "login-streak-vip",
      campaignSlug: "login-grand-prize",
      name: "连续登录领取会员时长",
      description: "连续登录达到阈值后，补发会员时长并继续冲刺大奖文案",
      taskType: "login_streak",
      eventType: "user.login",
      rewardAsset: "vip_duration",
      rewardAmount: 3,
      rewardRecipient: "actor",
      thresholdValue: 7,
      thresholdUnit: "day",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "streak",
      decayPolicy: "preview_only",
      riskRules: {
        freezeOn: [],
      },
      products: ["orbitchat", "ai", "ecommerce"],
      meta: {
        prizeCopy: "连续 30 天可冲刺 iPhone 17 大奖池",
        projectionSubscriptionType: "monthly",
      },
      status: "active",
      sortOrder: 50,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-order-paid-points",
      slug: "order-paid-points",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "下单支付返积分",
      description: "支付完成后，为当前用户返还积分",
      taskType: "order_paid",
      eventType: "order.paid",
      rewardAsset: "points",
      rewardAmount: 100,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "order",
      dailyLimit: null,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "none",
      riskRules: {
        freezeOn: ["matched_risk_list"],
      },
      products: ["ecommerce", "ai", "orbitchat"],
      meta: {
        minimumOrderAmount: 20,
      },
      status: "active",
      sortOrder: 60,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-subscription-upgrade-vip",
      slug: "subscription-upgrade-vip",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "会员升级补时长",
      description: "升级会员后，给当前用户追加会员时长资产",
      taskType: "subscription_upgrade",
      eventType: "subscription.upgraded",
      rewardAsset: "vip_duration",
      rewardAmount: 30,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "upgrade",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "repeatable",
      decayPolicy: "none",
      riskRules: {
        freezeOn: [],
      },
      products: ["orbitchat", "ai"],
      meta: {
        projectionSubscriptionType: "monthly",
      },
      status: "active",
      sortOrder: 70,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "template-ai-quota-exhausted-relief",
      slug: "ai-quota-exhausted-relief",
      campaignSlug: "vip-upgrade-flash-sale",
      name: "次数耗尽补偿积分",
      description: "次数耗尽后记录一次营销触达，并补发少量积分引导继续任务",
      taskType: "quota_relief",
      eventType: "ai.quota.exhausted",
      rewardAsset: "points",
      rewardAmount: 15,
      rewardRecipient: "actor",
      thresholdValue: 1,
      thresholdUnit: "trigger",
      dailyLimit: 1,
      lifetimeLimit: null,
      recurrence: "daily",
      decayPolicy: "none",
      riskRules: {
        freezeOn: [],
      },
      products: ["ai"],
      meta: {
        followUpTasks: ["ad-watch-ai-quota", "referral-register-cash"],
      },
      status: "active",
      sortOrder: 80,
      createdAt,
      updatedAt: createdAt,
    },
  ]
}
